

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_menu = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_quiz = new javax.swing.JButton();
        btn_store = new javax.swing.JButton();
        btn_donation = new javax.swing.JButton();
        parent_p = new javax.swing.JPanel();
        p_home = new javax.swing.JPanel();
        label_quizAttempt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_attemptQuiz = new javax.swing.JButton();
        p_news = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p_quiz = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p_displayQuiz = new javax.swing.JPanel();
        p_question = new javax.swing.JPanel();
        optionA = new javax.swing.JRadioButton();
        optionB = new javax.swing.JRadioButton();
        optionC = new javax.swing.JRadioButton();
        optionD = new javax.swing.JRadioButton();
        p_result = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p_store = new javax.swing.JPanel();
        p_merchandise = new javax.swing.JPanel();
        p_object1 = new javax.swing.JPanel();
        image1 = new javax.swing.JPanel();
        name_obj1 = new javax.swing.JLabel();
        quantity_obj1 = new javax.swing.JLabel();
        inputQuantity_obj1 = new javax.swing.JTextField();
        point_obj1 = new javax.swing.JLabel();
        add_obj1 = new javax.swing.JButton();
        p_object2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_plantTree = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p_donation = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_menu.setBackground(new java.awt.Color(134, 167, 137));

        btn_home.setBackground(new java.awt.Color(134, 167, 137));
        btn_home.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setText("HOME");
        btn_home.setToolTipText("home");
        btn_home.setBorder(null);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_quiz.setBackground(new java.awt.Color(134, 167, 137));
        btn_quiz.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btn_quiz.setForeground(new java.awt.Color(255, 255, 255));
        btn_quiz.setText("QUIZ");
        btn_quiz.setBorder(null);
        btn_quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quizActionPerformed(evt);
            }
        });

        btn_store.setBackground(new java.awt.Color(134, 167, 137));
        btn_store.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btn_store.setForeground(new java.awt.Color(255, 255, 255));
        btn_store.setText("STORE");
        btn_store.setBorder(null);
        btn_store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_storeActionPerformed(evt);
            }
        });

        btn_donation.setBackground(new java.awt.Color(134, 167, 137));
        btn_donation.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btn_donation.setForeground(new java.awt.Color(255, 255, 255));
        btn_donation.setText("DONATION");
        btn_donation.setBorder(null);
        btn_donation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_menuLayout = new javax.swing.GroupLayout(p_menu);
        p_menu.setLayout(p_menuLayout);
        p_menuLayout.setHorizontalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_store, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_donation, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_menuLayout.setVerticalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_menuLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_store, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_donation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        parent_p.setBackground(new java.awt.Color(235, 243, 232));
        parent_p.setLayout(new java.awt.CardLayout());

        p_home.setBackground(new java.awt.Color(235, 243, 232));

        label_quizAttempt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        label_quizAttempt.setText("Home");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_attemptQuiz.setBackground(new java.awt.Color(0, 0, 0));
        btn_attemptQuiz.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btn_attemptQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btn_attemptQuiz.setText("Quiz Attempt");
        btn_attemptQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attemptQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(btn_attemptQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(btn_attemptQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        p_news.setBackground(new java.awt.Color(235, 243, 232));
        p_news.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 167, 137)));

        javax.swing.GroupLayout p_newsLayout = new javax.swing.GroupLayout(p_news);
        p_news.setLayout(p_newsLayout);
        p_newsLayout.setHorizontalGroup(
            p_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        p_newsLayout.setVerticalGroup(
            p_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Top 5 News About Nature");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setText("Merchandise");

        javax.swing.GroupLayout p_homeLayout = new javax.swing.GroupLayout(p_home);
        p_home.setLayout(p_homeLayout);
        p_homeLayout.setHorizontalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_homeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_quizAttempt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_homeLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_news, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_homeLayout.createSequentialGroup()
                    .addGap(565, 565, 565)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(565, Short.MAX_VALUE)))
        );
        p_homeLayout.setVerticalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_homeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_quizAttempt)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_news, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_homeLayout.createSequentialGroup()
                    .addGap(414, 414, 414)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );

        parent_p.add(p_home, "card3");

        p_quiz.setBackground(new java.awt.Color(235, 243, 232));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Quiz");

        p_displayQuiz.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_questionLayout = new javax.swing.GroupLayout(p_question);
        p_question.setLayout(p_questionLayout);
        p_questionLayout.setHorizontalGroup(
            p_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        p_questionLayout.setVerticalGroup(
            p_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        optionA.setText("jRadioButton1");

        optionB.setText("jRadioButton2");

        optionC.setText("jRadioButton3");

        optionD.setText("jRadioButton4");

        javax.swing.GroupLayout p_resultLayout = new javax.swing.GroupLayout(p_result);
        p_result.setLayout(p_resultLayout);
        p_resultLayout.setHorizontalGroup(
            p_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_resultLayout.setVerticalGroup(
            p_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_displayQuizLayout = new javax.swing.GroupLayout(p_displayQuiz);
        p_displayQuiz.setLayout(p_displayQuizLayout);
        p_displayQuizLayout.setHorizontalGroup(
            p_displayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_displayQuizLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(p_displayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionD)
                    .addComponent(optionC)
                    .addComponent(optionB)
                    .addComponent(optionA)
                    .addComponent(p_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        p_displayQuizLayout.setVerticalGroup(
            p_displayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_displayQuizLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(p_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionD)
                .addGap(18, 18, 18)
                .addComponent(p_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(235, 243, 232));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("History");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_quizLayout = new javax.swing.GroupLayout(p_quiz);
        p_quiz.setLayout(p_quizLayout);
        p_quizLayout.setHorizontalGroup(
            p_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_quizLayout.createSequentialGroup()
                .addGroup(p_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p_quizLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(p_displayQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_quizLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        p_quizLayout.setVerticalGroup(
            p_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_quizLayout.createSequentialGroup()
                .addGroup(p_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_quizLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_quizLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(p_displayQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        parent_p.add(p_quiz, "card2");

        p_store.setBackground(new java.awt.Color(235, 243, 232));
        p_store.setLayout(new java.awt.CardLayout());

        p_merchandise.setBackground(new java.awt.Color(235, 243, 232));

        p_object1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout image1Layout = new javax.swing.GroupLayout(image1);
        image1.setLayout(image1Layout);
        image1Layout.setHorizontalGroup(
            image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        image1Layout.setVerticalGroup(
            image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        name_obj1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_obj1.setText("canvas bag");

        quantity_obj1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quantity_obj1.setText("Quantity");

        inputQuantity_obj1.setText("jTextField1");
        inputQuantity_obj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQuantity_obj1ActionPerformed(evt);
            }
        });

        point_obj1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        point_obj1.setForeground(new java.awt.Color(134, 167, 137));
        point_obj1.setText("20 points");

        add_obj1.setBackground(new java.awt.Color(0, 0, 0));
        add_obj1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        add_obj1.setForeground(new java.awt.Color(255, 255, 255));
        add_obj1.setText("Add");
        add_obj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_obj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_object1Layout = new javax.swing.GroupLayout(p_object1);
        p_object1.setLayout(p_object1Layout);
        p_object1Layout.setHorizontalGroup(
            p_object1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_object1Layout.createSequentialGroup()
                .addGroup(p_object1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_object1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(name_obj1))
                    .addGroup(p_object1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(point_obj1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_object1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(p_object1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_object1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(quantity_obj1)
                                .addGap(18, 18, 18)
                                .addComponent(inputQuantity_obj1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_object1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(add_obj1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        p_object1Layout.setVerticalGroup(
            p_object1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_object1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_obj1)
                .addGap(18, 18, 18)
                .addComponent(point_obj1)
                .addGap(18, 18, 18)
                .addGroup(p_object1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQuantity_obj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_obj1))
                .addGap(27, 27, 27)
                .addComponent(add_obj1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        p_object2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_object2Layout = new javax.swing.GroupLayout(p_object2);
        p_object2.setLayout(p_object2Layout);
        p_object2Layout.setHorizontalGroup(
            p_object2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_object2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        p_object2Layout.setVerticalGroup(
            p_object2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_object2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("Merchandise");

        javax.swing.GroupLayout p_merchandiseLayout = new javax.swing.GroupLayout(p_merchandise);
        p_merchandise.setLayout(p_merchandiseLayout);
        p_merchandiseLayout.setHorizontalGroup(
            p_merchandiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_merchandiseLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(p_merchandiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_merchandiseLayout.createSequentialGroup()
                        .addComponent(p_object1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(p_object2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(539, Short.MAX_VALUE))
                    .addGroup(p_merchandiseLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        p_merchandiseLayout.setVerticalGroup(
            p_merchandiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_merchandiseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_merchandiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_object2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_object1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        p_store.add(p_merchandise, "card2");

        p_plantTree.setBackground(new java.awt.Color(235, 243, 232));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setText("Plant a Tree");

        javax.swing.GroupLayout p_plantTreeLayout = new javax.swing.GroupLayout(p_plantTree);
        p_plantTree.setLayout(p_plantTreeLayout);
        p_plantTreeLayout.setHorizontalGroup(
            p_plantTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_plantTreeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1111, Short.MAX_VALUE))
        );
        p_plantTreeLayout.setVerticalGroup(
            p_plantTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_plantTreeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(805, Short.MAX_VALUE))
        );

        p_store.add(p_plantTree, "card3");

        parent_p.add(p_store, "card4");

        p_donation.setBackground(new java.awt.Color(235, 243, 232));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setText("Donation");

        javax.swing.GroupLayout p_donationLayout = new javax.swing.GroupLayout(p_donation);
        p_donation.setLayout(p_donationLayout);
        p_donationLayout.setHorizontalGroup(
            p_donationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_donationLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addContainerGap(1176, Short.MAX_VALUE))
        );
        p_donationLayout.setVerticalGroup(
            p_donationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_donationLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(814, Short.MAX_VALUE))
        );

        parent_p.add(p_donation, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parent_p, javax.swing.GroupLayout.DEFAULT_SIZE, 1348, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(p_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent_p, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        //click button home
        parent_p.removeAll(); //parent_p stand for parent panel
        parent_p.add(p_home);
        parent_p.repaint();
        parent_p.revalidate();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quizActionPerformed
        //click button quiz
        parent_p.removeAll();
        parent_p.add(p_quiz);
        parent_p.repaint();
        parent_p.revalidate();
    }//GEN-LAST:event_btn_quizActionPerformed

    private void btn_storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_storeActionPerformed
         //click button store
        parent_p.removeAll();
        parent_p.add(p_store);
        parent_p.repaint();
        parent_p.revalidate();
    }//GEN-LAST:event_btn_storeActionPerformed

    private void btn_donationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donationActionPerformed
        //click button donation
        parent_p.removeAll();
        parent_p.add(p_donation);
        parent_p.repaint();
        parent_p.revalidate();
    }//GEN-LAST:event_btn_donationActionPerformed

    private void btn_attemptQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attemptQuizActionPerformed
        //click button quiz attempt
        parent_p.removeAll();
        parent_p.add(p_quiz);
        parent_p.repaint();
        parent_p.revalidate();
    }//GEN-LAST:event_btn_attemptQuizActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputQuantity_obj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuantity_obj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQuantity_obj1ActionPerformed

    private void add_obj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_obj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_obj1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_obj1;
    private javax.swing.JButton btn_attemptQuiz;
    private javax.swing.JButton btn_donation;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_quiz;
    private javax.swing.JButton btn_store;
    private javax.swing.JPanel image1;
    private javax.swing.JTextField inputQuantity_obj1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_quizAttempt;
    private javax.swing.JLabel name_obj1;
    private javax.swing.JRadioButton optionA;
    private javax.swing.JRadioButton optionB;
    private javax.swing.JRadioButton optionC;
    private javax.swing.JRadioButton optionD;
    private javax.swing.JPanel p_displayQuiz;
    private javax.swing.JPanel p_donation;
    private javax.swing.JPanel p_home;
    private javax.swing.JPanel p_menu;
    private javax.swing.JPanel p_merchandise;
    private javax.swing.JPanel p_news;
    private javax.swing.JPanel p_object1;
    private javax.swing.JPanel p_object2;
    private javax.swing.JPanel p_plantTree;
    private javax.swing.JPanel p_question;
    private javax.swing.JPanel p_quiz;
    private javax.swing.JPanel p_result;
    private javax.swing.JPanel p_store;
    private javax.swing.JPanel parent_p;
    private javax.swing.JLabel point_obj1;
    private javax.swing.JLabel quantity_obj1;
    // End of variables declaration//GEN-END:variables
}
