
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tan Zhi Wei
 */
public class forgottenPassword extends javax.swing.JFrame {

    /**
     * Creates new form forgottenPassword
     */
    
    public forgottenPassword() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newPasswordEntered1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetPWbtn = new javax.swing.JButton();
        cfNewPassword1 = new javax.swing.JPasswordField();
        iconDisable1 = new javax.swing.JLabel();
        iconShow1 = new javax.swing.JLabel();
        iconDisable2 = new javax.swing.JLabel();
        iconShow2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 243, 232));

        newPasswordEntered1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordEntered1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Reset Password");

        jLabel2.setText("New Password");

        jLabel1.setText("Confirm New Password");

        resetPWbtn.setText("Reset Password");
        resetPWbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPWbtnActionPerformed(evt);
            }
        });

        iconDisable1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icon\\closeeye.png"));
        iconDisable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconDisable1MousePressed(evt);
            }
        });

        iconShow1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icon\\openeye.png"));
        iconShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconShow1MousePressed(evt);
            }
        });

        iconDisable2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icon\\closeeye.png"));
        iconDisable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconDisable2MousePressed(evt);
            }
        });

        iconShow2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icon\\openeye.png"));
        iconShow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconShow2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(jLabel4)
                .addGap(0, 1142, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cfNewPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(newPasswordEntered1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconDisable1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconDisable2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(731, 731, 731)
                        .addComponent(resetPWbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(511, 511, 511)
                    .addComponent(jLabel2)
                    .addContainerGap(1379, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel4)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordEntered1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconDisable1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cfNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iconShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconDisable2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(resetPWbtn)
                .addContainerGap(549, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(jLabel2)
                    .addContainerGap(776, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void resetPWbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPWbtnActionPerformed
        PasswordRecovery recover = new PasswordRecovery();
        if(evt.getSource() == resetPWbtn){
            String newPassword = newPasswordEntered1.getText();
            String confirmPassword = cfNewPassword1.getText();
            if(recover.updateUserPassword(newPassword, confirmPassword)){
                JOptionPane.showMessageDialog(null,"You had reset your password successfully.");   
                setVisible(false);
                new real_login_gui().setVisible(true);
                }
            else{
                JOptionPane.showMessageDialog(null,"Please make sure your new password same with comfirm new password.");  
            }
            
        }
    }//GEN-LAST:event_resetPWbtnActionPerformed

    private void newPasswordEntered1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordEntered1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordEntered1ActionPerformed

    private void iconDisable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconDisable1MousePressed
        iconDisable1.setVisible(false);
        iconShow1.setEnabled(true);
        newPasswordEntered1.setEchoChar((char)0);
    }//GEN-LAST:event_iconDisable1MousePressed

    private void iconShow1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShow1MousePressed
        iconDisable1.setVisible(true);
        iconShow1.setEnabled(false);
        newPasswordEntered1.setEchoChar('*');
    }//GEN-LAST:event_iconShow1MousePressed

    private void iconDisable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconDisable2MousePressed
        iconDisable2.setVisible(false);
        iconShow2.setEnabled(true);
        cfNewPassword1.setEchoChar((char)0);
    }//GEN-LAST:event_iconDisable2MousePressed

    private void iconShow2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShow2MousePressed
        iconDisable2.setVisible(true);
        iconShow2.setEnabled(false);
        cfNewPassword1.setEchoChar('*');
    }//GEN-LAST:event_iconShow2MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cfNewPassword1;
    private javax.swing.JLabel iconDisable1;
    private javax.swing.JLabel iconDisable2;
    private javax.swing.JLabel iconShow1;
    private javax.swing.JLabel iconShow2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPasswordEntered1;
    private javax.swing.JButton resetPWbtn;
    // End of variables declaration//GEN-END:variables
}
